name: Test

on: 
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v6

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install Asciidoctor
      run: gem install asciidoctor -v '>= 2.0.18'

    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release --target all

    - name: Test
      run: ctest --test-dir build -C Release --output-on-failure -VV

    - name: Install
      run: cmake --install build --config Release --prefix stage


  emscripten:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set Up Emscripten
      uses: mymindstorm/setup-emsdk@v16
      with:
        version: 3.1.70
        actions-cache-folder: 'emsdk-cache'

    - name: Configure
      shell: bash
      run: |
        cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake \
                            -DCMAKE_BUILD_TYPE=Release


    - name: Build
      shell: bash
      run: cmake --build build --config Release --target all

    - name: Test
      shell: bash
      run: ctest --test-dir build -C Release --output-on-failure -VV
  
