name: Test

on: 
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install Asciidoctor
      run: gem install asciidoctor -v '>= 2.0.18'

    - name: Configure CMake
      run: |
        cmake -E make_directory build
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build and Test
      run: cmake --build build --config Release --target all run-tests

    - name: Install
      run: cmake --install build --config Release --prefix stage

    # - name: Archive production artifacts
    #   if: always()
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: patch-logs-${{ matrix.os }}
    #     path: |
    #       build/_deps/util-linux-subbuild/util-linux-populate-prefix/src/util-linux-populate-stamp/util-linux-populate-patch-*.*

  emscripten:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Up Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.70
        actions-cache-folder: 'emsdk-cache'

    - name: Configure
      shell: bash
      run: |
        cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake \
                            -DCMAKE_BUILD_TYPE=Release


    - name: Build and Test
      shell: bash
      run: cmake --build build --target all run-tests
  
