name: Test

on: 
  push:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'

env:
  BUILD_TYPE: Release

jobs:
  desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install Asciidoctor
      run: gem install asciidoctor -v '>= 2.0.18'

    - name: Configure CMake
      run: |
        cmake -E make_directory build
        cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build and Test
      run: cmake --build build --config ${{ env.BUILD_TYPE }} --target all run-tests

    - name: Install
      run: cmake --install build --config ${{ env.BUILD_TYPE }} --prefix stage

    - name: Archive production artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: patch-logs-${{ matrix.os }}
        path: |
          build/_deps/util-linux-subbuild/util-linux-populate-prefix/src/util-linux-populate-stamp/util-linux-populate-patch-*.*

